telemetry:
  enabled: false

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher
  config:
    env_vars:
      - PYTHONPATH

storage:
  sqlite:
    base_dir: /opt/dagster/dagster_home

compute_logs:
  module: dagster.core.storage.compute_logs
  class: FilesystemComputeLogManager
  config:
    base_dir: /opt/dagster/dagster_home/compute_logs

local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: /opt/dagster/dagster_home/storage 