services:
  base:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.base
    image: sherlog-parser-base:latest

  dagster:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.dagster
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app:ro
      - dagster_home:/opt/dagster/dagster_home
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - PYTHONPATH=/app
    depends_on:
      - base
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  streamlit:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.ui
    ports:
      - "8501:8501"
    volumes:
      - ../../:/app:ro
      - log_data:/data/logs
      - cache_data:/data/cache
    environment:
      - DAGSTER_HOST=dagster
      - DAGSTER_PORT=3000
      - PYTHONPATH=/app
    depends_on:
      dagster:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  dagster_home:
  log_data:
  cache_data: 